### ISSUE TITLE
Actual CLI instead of gulp

### ISSUE THREAD

**Issue by damnhipster** [skyglobal/gulp-component-helper#25]
Having `gulp serve` is cool and all, but something like `bowerize serve` or `bowerize upload` would be even cooler.

Also, a CLI can give a better `--help` to use and refer to rather than `GULP-TASKS.md`.

Check out [ember-cli](http://www.ember-cli.com/#getting-started) for an example of what I mean.

**Comment by peter-mouland** [comment]
i've been mulling this over as well, was thinking about maybe [Yoeman](http://yeoman.io/). 

a cli would be über cool, you found any docs on how to create a cli. i think i'ts a npm module with a sym-link to the npm/bin directory...

**Comment by damnhipster** [comment]
I've hacked a node package with a CLI [here](https://github.com/damnhipster/node-cli-package).

You basically have to create a `bin/` directory with your executable node script, and list that in your `package.json`. The example above does some argument parsing and module requires. It should be quite easy to turn `gulp-component-helper` into a CLI.

**Comment by peter-mouland** [comment]
lets explore this CLI route further before switching to Yoeman or anything :)
https://github.com/skyglobal/gulp-component-helper/pull/27
