### ISSUE TITLE
Author not set correctly on bower.json

### ISSUE THREAD

**Issue by damnhipster** [skyglobal/gulp-component-helper#28]
Not sure why :confused: 

Looks like this when creating a new component:

```js
{
    "name": "bskyb-tooltip",
    "version": "0.0.0",
    "homepage": "https://github.com/damnhipster/tooltip",
    "authors": [
        "git.user-name <{{ git.user-email }}>"
    ],
...
```

**Comment by peter-mouland** [comment]
I haven't bumped the version number yet with your updates...
I'll be getting in screenshotting shortly. 
I'll come over in the morning after standup, and try and smooth some edges then we can get 0.5.0 out

**Comment by peter-mouland** [comment]
should be sorted now the latest release is in npm
